'use client'
import { useEffect, useState } from 'react'
import { TaxData } from '@/lib/types'
import TaxSummary from '@/components/TaxSummary'
import OptimizationsList from '@/components/OptimizationsList'
import IncomeTable from '@/components/IncomeTable'
import RSUCorrections from '@/components/RSUCorrections'
import DeductionsCard from '@/components/DeductionsCard'
import CreditsCard from '@/components/CreditsCard'
import TaxChart from '@/components/TaxChart'
import StateReturns from '@/components/StateReturns'
import DocumentChecklist from '@/components/DocumentChecklist'
import AuditTrail from '@/components/AuditTrail'

export default function Dashboard() {
  const [data, setData] = useState<TaxData | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    // Try loading from output first, fall back to sample data
    const paths = [
      '/api/tax-data', // API route that reads from output/
      '/sample-data.json', // Fallback sample data
    ]

    async function loadData() {
      for (const path of paths) {
        try {
          const res = await fetch(path)
          if (res.ok) {
            const json = await res.json()
            setData(json)
            return
          }
        } catch {}
      }
      setError('No tax data found. Run /tax-prepare first, or place sample-data.json in dashboard/public/')
    }

    loadData()
  }, [])

  if (error) return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-center p-8">
        <h1 className="text-2xl font-bold mb-4">No Tax Data</h1>
        <p className="text-gray-500 mb-4">{error}</p>
        <code className="bg-gray-100 px-4 py-2 rounded text-sm">claude &gt; /tax-prepare</code>
      </div>
    </div>
  )

  if (!data) return (
    <div className="min-h-screen flex items-center justify-center">
      <p className="text-gray-400">Loading...</p>
    </div>
  )

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b px-6 py-4 flex justify-between items-center sticky top-0 z-10">
        <div>
          <h1 className="text-xl font-bold">your-tax-agent</h1>
          <p className="text-sm text-gray-500">{data.taxYear} Tax Return &mdash; {data.filingStatus}</p>
        </div>
        <div className="text-right">
          <p className="text-sm text-gray-500">{data.primary.name}{data.spouse ? ` & ${data.spouse.name}` : ''}</p>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8">
        <TaxSummary data={data} />
        <OptimizationsList optimizations={data.optimizations} />

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <DeductionsCard data={data} />
          <CreditsCard data={data} />
        </div>

        <TaxChart data={data} />
        <IncomeTable data={data} />
        <RSUCorrections data={data} />
        <StateReturns data={data} />
        <DocumentChecklist items={data.documentChecklist} />
        {data.audit && <AuditTrail data={data.audit} />}
      </main>

      <footer className="text-center py-6 text-xs text-gray-400">
        Generated by your-tax-agent. Not professional tax advice. Consult a CPA for final filing decisions.
      </footer>
    </div>
  )
}
