'use client'
import { useEffect, useState } from 'react'
import { useTaxStore } from '@/lib/store'
import { TaxData } from '@/lib/types'
import TaxSummary from '@/components/dashboard/TaxSummary'
import OptimizationsList from '@/components/dashboard/OptimizationsList'
import IncomeTable from '@/components/dashboard/IncomeTable'
import RSUCorrections from '@/components/dashboard/RSUCorrections'
import DeductionsCard from '@/components/dashboard/DeductionsCard'
import CreditsCard from '@/components/dashboard/CreditsCard'
import TaxChart from '@/components/dashboard/TaxChart'
import StateReturns from '@/components/dashboard/StateReturns'
import DocumentChecklist from '@/components/dashboard/DocumentChecklist'
import AuditTrail from '@/components/dashboard/AuditTrail'
import Link from 'next/link'
import { ArrowLeft, Download, FileText } from 'lucide-react'

export default function DashboardPage() {
  const storeResults = useTaxStore((s) => s.results)
  const [data, setData] = useState<TaxData | null>(null)

  useEffect(() => {
    if (storeResults) {
      setData(storeResults)
      return
    }

    // Fallback: load sample data for demo
    fetch('/sample-data.json')
      .then(r => r.json())
      .then(setData)
      .catch(() => {})
  }, [storeResults])

  if (!data) return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="text-center p-8">
        <h1 className="text-2xl font-bold mb-4">No Tax Data</h1>
        <p className="text-gray-500 mb-6">Run the analysis first, or view the demo.</p>
        <Link href="/setup" className="bg-green-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-green-700">
          Get Started
        </Link>
      </div>
    </div>
  )

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b px-6 py-4 flex justify-between items-center sticky top-0 z-10">
        <div className="flex items-center gap-4">
          <Link href="/" className="text-gray-400 hover:text-gray-600">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h1 className="text-lg font-bold">your-tax-agent</h1>
            <p className="text-xs text-gray-500">{data.taxYear} Tax Return &mdash; {data.filingStatus}</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-sm text-gray-500">{data.primary.name}{data.spouse ? ` & ${data.spouse.name}` : ''}</span>
          <button className="flex items-center gap-1.5 border px-3 py-1.5 rounded-lg text-sm hover:bg-gray-50">
            <Download className="w-3.5 h-3.5" /> PDF
          </button>
          <button className="flex items-center gap-1.5 border px-3 py-1.5 rounded-lg text-sm hover:bg-gray-50">
            <FileText className="w-3.5 h-3.5" /> CPA Guide
          </button>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8">
        <TaxSummary data={data} />
        <OptimizationsList optimizations={data.optimizations} />

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <DeductionsCard data={data} />
          <CreditsCard data={data} />
        </div>

        <TaxChart data={data} />
        <IncomeTable data={data} />
        <RSUCorrections data={data} />
        <StateReturns data={data} />
        <DocumentChecklist items={data.documentChecklist} />
        {data.audit && <AuditTrail data={data.audit} />}
      </main>

      <footer className="text-center py-6 text-xs text-gray-400">
        Generated by your-tax-agent. Not professional tax advice. Consult a CPA for final filing decisions.
      </footer>
    </div>
  )
}
