'use client'
import { useEffect, useState } from 'react'
import { useTaxStore } from '@/lib/store'
import { TaxData } from '@/lib/types'
import TaxSummary from '@/components/dashboard/TaxSummary'
import OptimizationsList from '@/components/dashboard/OptimizationsList'
import IncomeTable from '@/components/dashboard/IncomeTable'
import RSUCorrections from '@/components/dashboard/RSUCorrections'
import DeductionsCard from '@/components/dashboard/DeductionsCard'
import CreditsCard from '@/components/dashboard/CreditsCard'
import TaxChart from '@/components/dashboard/TaxChart'
import StateReturns from '@/components/dashboard/StateReturns'
import DocumentChecklist from '@/components/dashboard/DocumentChecklist'
import AuditTrail from '@/components/dashboard/AuditTrail'
import Link from 'next/link'
import { ArrowLeft, Download, FileText } from 'lucide-react'

function generateCPAGuide(data: TaxData): string {
  const fmt = (n: number) => n.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })

  let md = `# ${data.taxYear} Tax Filing Guide\n`
  md += `## ${data.primary.name}${data.spouse ? ` & ${data.spouse.name}` : ''} — ${data.filingStatus}\n\n`
  md += `**Expected Federal Refund:** ${fmt(data.summary.federalRefund)}\n`
  md += `**NY Refund:** ${fmt(data.summary.nyRefund)}\n`
  md += `**NJ Owed:** ${fmt(data.summary.njOwed)}\n\n`

  md += `## Optimizations Applied\n\n`
  data.optimizations.forEach(o => {
    md += `- **${o.name}** — ${fmt(o.savings)} saved (${o.risk})\n  ${o.description}\n`
  })

  md += `\n## Income Summary\n\n`
  md += `| Source | Amount |\n|---|---|\n`
  md += `| ${data.primary.name} W-2 | ${fmt(data.income.wages.primary.wages)} |\n`
  if (data.income.wages.spouse) md += `| ${data.spouse?.name} W-2 | ${fmt(data.income.wages.spouse.wages)} |\n`
  md += `| Dividends | ${fmt(data.income.dividends.ordinary)} |\n`
  md += `| Interest | ${fmt(data.income.interest)} |\n`
  md += `| Capital Gains (net) | ${fmt(data.income.capitalGains.net)} |\n`
  if (data.income.scheduleC) md += `| Schedule C (${data.income.scheduleC.businessName}) | ${fmt(data.income.scheduleC.net)} |\n`
  md += `| **AGI** | **${fmt(data.income.agi)}** |\n`

  md += `\n## Deductions (${data.deductions.method})\n\n`
  md += `| Deduction | Amount |\n|---|---|\n`
  md += `| Mortgage Interest | ${fmt(data.deductions.itemized.mortgageInterest)} |\n`
  md += `| Points | ${fmt(data.deductions.itemized.points)} |\n`
  md += `| SALT (capped) | ${fmt(data.deductions.itemized.salt)} |\n`
  md += `| Charitable | ${fmt(data.deductions.itemized.charitable)} |\n`
  md += `| **Total Itemized** | **${fmt(data.deductions.itemized.total)}** |\n`

  md += `\n## Credits\n\n`
  if (data.credits.solar) md += `- Solar (30%): ${fmt(data.credits.solar.credit)}\n`
  if (data.credits.foreignTax) md += `- Foreign Tax: ${fmt(data.credits.foreignTax)}\n`
  md += `- **Total Credits:** ${fmt(data.credits.total)}\n`

  md += `\n## Tax Calculation\n\n`
  md += `| Line | Amount |\n|---|---|\n`
  md += `| Taxable Income | ${fmt(data.taxCalculation.taxableIncome)} |\n`
  md += `| Income Tax | ${fmt(data.taxCalculation.incomeTax)} |\n`
  md += `| Additional Medicare | ${fmt(data.taxCalculation.additionalMedicare)} |\n`
  md += `| NIIT | ${fmt(data.taxCalculation.niit)} |\n`
  md += `| Credits | -${fmt(data.taxCalculation.totalCredits)} |\n`
  md += `| **Net Tax** | **${fmt(data.taxCalculation.netTax)}** |\n`
  md += `| Withholding | ${fmt(data.taxCalculation.totalWithholding)} |\n`
  md += `| **Refund** | **${fmt(data.taxCalculation.result)}** |\n`

  if (data.rsuCorrections) {
    md += `\n## RSU Basis Corrections (Form 8949)\n\n`
    md += `**Combined phantom income eliminated:** ${fmt(data.rsuCorrections.primary.phantomIncomeEliminated + (data.rsuCorrections.spouse?.phantomIncomeEliminated || 0))}\n`
    md += `**Tax saved:** ${fmt(data.rsuCorrections.combinedSavings)}\n\n`
    md += `Report on Form 8949 Part I, Box B (short-term, basis not reported to IRS).\n`
  }

  md += `\n## State Returns\n\n`
  md += `- **NY (IT-203):** Refund ${fmt(data.stateReturns.ny.refund)}\n`
  md += `- **NJ (NJ-1040):** Owed ${fmt(data.stateReturns.nj.owed)}\n`
  md += `- File NY first, then NJ.\n`

  md += `\n## Document Checklist\n\n`
  data.documentChecklist.forEach(d => {
    md += `- [${d.status === 'complete' ? 'x' : ' '}] ${d.name}\n`
  })

  md += `\n---\n*Generated by your-tax-agent. Not professional tax advice.*\n`
  return md
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function downloadJSON(data: TaxData, filename: string) {
  downloadFile(JSON.stringify(data, null, 2), filename, 'application/json')
}

export default function DashboardPage() {
  const storeResults = useTaxStore((s) => s.results)
  const [data, setData] = useState<TaxData | null>(null)

  useEffect(() => {
    if (storeResults) {
      setData(storeResults)
      return
    }

    // Fallback: load sample data for demo
    fetch('/sample-data.json')
      .then(r => r.json())
      .then(setData)
      .catch(() => {})
  }, [storeResults])

  if (!data) return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="text-center p-8">
        <h1 className="text-2xl font-bold mb-4">No Tax Data</h1>
        <p className="text-gray-500 mb-6">Run the analysis first, or view the demo.</p>
        <Link href="/setup" className="bg-green-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-green-700">
          Get Started
        </Link>
      </div>
    </div>
  )

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b px-6 py-4 flex justify-between items-center sticky top-0 z-10">
        <div className="flex items-center gap-4">
          <Link href="/" className="text-gray-400 hover:text-gray-600">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h1 className="text-lg font-bold">your-tax-agent</h1>
            <p className="text-xs text-gray-500">{data.taxYear} Tax Return &mdash; {data.filingStatus}</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-sm text-gray-500">{data.primary.name}{data.spouse ? ` & ${data.spouse.name}` : ''}</span>
          <button
            onClick={() => downloadJSON(data, `${data.taxYear}_tax_return_data.json`)}
            className="flex items-center gap-1.5 border px-3 py-1.5 rounded-lg text-sm hover:bg-gray-50"
          >
            <Download className="w-3.5 h-3.5" /> Data
          </button>
          <button
            onClick={() => downloadFile(generateCPAGuide(data), `${data.taxYear}_filing_guide.md`, 'text/markdown')}
            className="flex items-center gap-1.5 border px-3 py-1.5 rounded-lg text-sm hover:bg-gray-50"
          >
            <FileText className="w-3.5 h-3.5" /> CPA Guide
          </button>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8">
        <TaxSummary data={data} />
        <OptimizationsList optimizations={data.optimizations} />

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <DeductionsCard data={data} />
          <CreditsCard data={data} />
        </div>

        <TaxChart data={data} />
        <IncomeTable data={data} />
        <RSUCorrections data={data} />
        <StateReturns data={data} />
        <DocumentChecklist items={data.documentChecklist} />
        {data.audit && <AuditTrail data={data.audit} />}
      </main>

      <footer className="text-center py-6 text-xs text-gray-400">
        Generated by your-tax-agent. Not professional tax advice. Consult a CPA for final filing decisions.
      </footer>
    </div>
  )
}
